sudo: required

env:
  - ODOO_VERSION=13.0

services:
  - docker

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG}:${ODOO_VERSION} .

script:
  - docker run -i -t --rm ${TRAVIS_REPO_SLUG}:${ODOO_VERSION}

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

deploy:
  - provider: script
    script: docker push ${TRAVIS_REPO_SLUG}:${ODOO_VERSION}
    on:
      branch: ${ODOO_VERSION}
